### ISSUE TITLE
top left of textbox not in the correct location

### ISSUE THREAD

**Issue by Oseriduun** [glitchroy/textboxy#1]
using the following code for example, you can see that the textbox does not correctly move the top left location when changing to the next queued item.

```
tbyAddAction(TbyAction.SetSpeaker, objPlayer);

tbyAddAction(TbyAction.ShowString, "This is the first line.");

tbyAddAction(TbyAction.ShowString, "What [c/red]crazy[r] and [c/orange]unique[r] adventures await?");

tbyAddAction(TbyAction.ShowString, "What the heck is going on here?\nWhy are you in my garden?\nGet out of here!");

tbyStart();

```

if the speaker moves once the textbox has been created, it will move to the correct location, otherwise the additional lines will cause the bottom of the textbox to overlap the speakers location.

**Comment by glitchroy** [comment]
Hey there, thanks for reporting! It looks like the bug occurs because `tbyActionShowString()` does not recalculate the textbox position if no `positionUpdate` (e.g. from the SetOrigin or SetPosition action) was scheduled. The position of a *moving* textbox still gets recalculated because it gets called every time the speaker instance moves.
I only tested this with one-liners, which is why I never encountered the bug.

Please test with the new version below (remove `textboxy` folders in Scripts and Objects and re-import) and report back. I will then close the issue.

[textbox-v0.2.2-beta.zip](https://github.com/glitchroy/textboxy/files/2050669/textbox-v0.2.2-beta.zip)

**Comment by Oseriduun** [comment]
i am unable to import anything from the .yymp file, gamemaker throws an error.  going to try and manually update the files in accordance with the commit changelog and get back to you afterwards.

**Comment by Oseriduun** [comment]
```
NPC Found: 100131
[TBY] Queue Begin | 
ERROR!!! :: ############################################################################################
FATAL ERROR in
action number 1
of Other Event: User Defined 2
for object tbyTextboxManager:


instance_exists argument 1 incorrect type (array) expecting a Number (YYGI32)
 at gml_Script_tbyActionSetSpeaker (line 9) - if (instance_exists(speaker)) {
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_tbyActionSetSpeaker (line 9)
called from - gml_Script_tbySpread (line 23) -     return script_execute(func, args[@ 0]);
called from - gml_Object_tbyTextboxManager_Other_12 (line 30) - tbySpread(actionScript, arguments);
called from - gml_Object_tbyTextboxManager_Other_11 (line 12) - tbyManagerNextAction;
called from - gml_Script_tbyStart (line 5) - 	tbyManagerStart;
called from - gml_Object_objNPC_Nivek_Other_10 (line 13) - tbyStart();
called from - gml_Object_objPlayer_KeyPress_69 (line 9) - 	with(_found) { event_user(0); }	

```

**Comment by glitchroy** [comment]
That's strange, it looks like the script receives a speaker that is an array instead of an instance. Do you still use the same code from above?

**Comment by Oseriduun** [comment]
after testing further, this particular issue is fixed. I will open a new bug issue report regarding the array problem from my previous comment

**Comment by Oseriduun** [comment]
just to confirm, all is working.. the more recent error was a my own fault
at not setting the profiles correctly. (i was trying to use
tbyAddAction(TbyAction.SetSpeaker, npc_nivek_) instead of
tbyProfile(npc_nivek_).

**Comment by glitchroy** [comment]
Glad to see it's resolved! I will release the new bugfix version soon then
