### ISSUE TITLE
Add debug toggle to tby_config()

### ISSUE THREAD

**Issue by xxxxvelocityxxxx** [glitchroy/textboxy#16]
Whenever I create a new textbox it has above it in small letters "6 | state:" and then whatever state it's in, whether its Writing or Finished. Is there any way to disable this? I'm assuming it's some sort of debug setting but I don't see anything about it in TbyOptions.

**Comment by glitchroy** [comment]
Woah hey now, this is old!  
For now, you can disable this behaviour by setting `global.tby_debug` in `tby_globals()` to false (`textboxy/Internal/Internal Docs/tby_globals`).  
I will keep this open for adding the debug toggle to the `tby_config`! (Sorry for not replying for like three months.)

**Comment by glitchroy** [comment]
Added `tby_debug_on_startup` macro in `tby_config()` in c73d7d3b8d428aa4969b264026fc6673b644b361 to control the intial debug state.
I think this should be sufficient for a debug option. Advanced behaviour can be implemented by just setting the `global.tby_debug` variable to true/false.
