### ISSUE TITLE
Alignement problem

### ISSUE THREAD

**Issue by batblaster** [glitchroy/textboxy#4]
I have used this text box system and i saw a problem using this settings:

SkinD
Calibri font 12 of size, bold
Using the text between man and old man in the documentation you can see the problem attached here:
![textbox](https://user-images.githubusercontent.com/2376502/49620022-c3126f80-f9f1-11e8-9fb4-993de1dae83a.jpg)

**Comment by glitchroy** [comment]
Thanks for reporting! It looks like the proper height is incorrectly calculated when using bigger fonts.  
Since the new version on the scribble-branch is handling that automatically, patching the old codebase is not worth it, in my opinion.
